# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neuralfile',
            options={'verbose_name': 'Neural File', 'verbose_name_plural': 'Neural Files'},
        ),
        migrations.AlterField(
            model_name='neuralfile',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='csv'),
        ),
        migrations.AlterModelTable(
            name='neuralfile',
            table='neural_file',
        ),
    ]
